name: Cron Job
on:
  schedule:
    - cron: '*/15 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: commitQueen
          persist-credentials: false
          fetch-depth: 0
      - name: 'Set up Python 3.x'
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: 'Make trash commits'
        run: |
          python commit_queen.py
          git config --local user.email "amanecer.luz.cabrera@gmail.com"
          git config --local user.name "Amy Lovelace"

          for n in range(random.randint(1, 6)):
            to_write = f'{random.choice(messages)}\n' * 100

            if n > 4:
              # Create the file
              os.system(f'echo "{to_write}" > "bin/generated-{random.randint(1, 10)}.txt"')

              # Add the file to the staging area
              git add "bin/generated-{random.randint(1, 10)}.txt"
            else:
              # Append to the file
              os.system(f'echo "{to_write}" >> bin/generated-{random.randint(1, 10)}.txt')

            os.system('git commit -m "{q(random.choice(messages))}"')
      - name: 'Push changes'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          force: 'true'
          branch: 'commitQueen'
