      
name: Cron Job
on:
 schedule:
   - cron: '*/15 * * * *' # Ejecuta el job cada 15 minutos
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: trunk
          persist-credentials: false 
          fetch-depth: 0 
      - name: 'Set up Python 3.x'
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: 'Make trash commits'
        run: |
         git config --local user.email "amanecer.luz.cabrera@gmail.com" # setup commit email
            git config --local user.name "Amy Lovelace" # setup commit name
          python commit_queen.py # actually make the commits
      - name: 'Push changes'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          force: 'true'
          branch: 'trunk'
           
