      
name: Cron Job
on:
 schedule:
   - cron: '*/15 * * * *' # Ejecuta el job cada 15 minutos
jobs:
 cron:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v2
     - name: Run script
       run: node /script.js
     - name: Commit and push if it changed
       run: |
         git diff
         git config --local user.email "amanecer.luz.cabrera@gmail.com" # setup commit email
            git config --local user.name "Amy Lovelace" # setup commit name
            git diff --quiet && git diff --staged --quiet || git commit -am "Add comment"
         git push

